### ISSUE TITLE
Improve Get Weather Behavior

### ISSUE THREAD

**Issue by danilobarion1986** [danilobarion1986/polling-with-react#17]
When we add coordinates and select a city from the list, is not clear from which data the forecast will be retrieved.
We need to improve the UX of the page, indicating what data will be used to get the weather.
We can maybe add two buttons, one for each type of data.

**Comment by le-santos** [comment]
Check the last PR's #19 and #20 
Now both inputs are tied. If you select a city, it inserts the coordinates values in text inputs. If you type, the select resets. Does it solve this issue?

**Comment by danilobarion1986** [comment]
> Check the last PR's #19 and #20 
> Now both inputs are tied. If you select a city, it inserts the coordinates values in text inputs. If you type, the select resets. Does it solve this issue?
> 

Sure, I think that for our scope, that is most practice/study than a production ready and fully-featured app, this solution is simple and works great! I'll take a look at the PR's tomorrow.

**Comment by danilobarion1986** [comment]
Closed by #19 and #20
