### ISSUE TITLE
After change location, GetWeather button doesn't work

### ISSUE THREAD

**Issue by danilobarion1986** [danilobarion1986/polling-with-react#18]
After we have loaded a forecast for some location, the GetWeather button doesn't work anymore when changing locations.

**Comment by le-santos** [comment]
If you check my pr #19 the form state flow is better, and the button keeps working after the request.
BESIDES that, it's still impossible to make a new request after the first one.. It seems that updating the geoData state doesn't trigger a new request, and ReactPolling doesn't uses new url, keeping a persistent connection with the old one. 
I'm checking on that!

**Comment by danilobarion1986** [comment]
Closed by #19
